### ISSUE TITLE
Change max. build amount to 0 if requirements for ship/defense are not met

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#125]
Currently the ship / defense popup calculates the max amount of units that can be built with the current resources on the planet.

As seen here on the right side of the screen, the max amount of units that can be built is 12:
![Image](https://github.com/lanedirt/OGameX/assets/6917405/f70c13d5-d8c4-4614-acdb-b8fd80670271)

TODO:
- The max. build amount should show "0" if the technology requirements for this object are not met (i.e. the object cannot be built). Change the template file for this ajax popup: `/resources/views/ingame/ajax/object.blade.php`.

**Comment by Danielopes7** [comment]
_/ObjectAjaxTrait.php_
```php
        $requirements_met = $objects->objectRequirementsMet($object->machine_name, $planet, $player);

        $price = $objects->getObjectPrice($object->machine_name, $planet);

        // Get max build amount of this object (unit).
        $max_build_amount = $objects->getObjectMaxBuildAmount($object->machine_name, $planet);
``` 
hey, can I change it here in the function ajaxHandler? like inserting a condition to `max_build_amount `be `0 `when `requirements_met `is `false`, or does the change need to be in `object.blade.php` ?

**Comment by lanedirt** [comment]
@Danielopes7 Yes I think adding the extra condition in the line you are refering to should work. What I mentioned in the original issue to change it directly in the template was not the best way I think now. Because with your suggestion the new value should automatically be passed on to the view template content, which is a nicer solution.

So +1 👍, looking forward to the PR!

**Comment by Danielopes7** [comment]
I've already made the change, I'm just fixing the tests and  I'll do the PR soon!

**Comment by Danielopes7** [comment]
> @Danielopes7 Yes I think adding the extra condition in the line you are refering to should work. What I mentioned in the original issue to change it directly in the template was not the best way I think now. Because with your suggestion the new value should automatically be passed on to the view template content, which is a nicer solution.
> 
> So +1 👍, looking forward to the PR!


I've already made the change, I'm just fixing the tests and I'll do the PR soon!
