### ISSUE TITLE
Show actual unit/planet counts in galaxy overview page

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#126]
Currently the galaxy page shows incorrect amounts for these areas:

Top:
- "Esp. Probe"
- "Recycler"
- "IPM"

Bottom:
- "X Planets Colonized"

TODO:
- Update the parts above so it reflects the actual amount of units on the current planet. The `PlanetService::getObjectAmount()` method can most likely be used for this.

See this example screenshot:

![Image](https://github.com/lanedirt/OGameX/assets/6917405/b81dccec-f719-488b-acbe-1a270b39afa0)

**Comment by gabrieltsants** [comment]
Hello!

I noticed that the "Esp. Probe" object seems to be correct. As for the "IPM", I fixed it by changing it to 'availableMissiles' => $planet->getObjectAmount('interplanetary_missile'), and I applied a similar fix to the recycler. Does this look correct, or did I miss something?

**Comment by lanedirt** [comment]
Hi @gabrieltsants,

Thanks for looking into this! The fix you're describing seems to be correct to me. If you could make a PR for it I'll gladly take a look and test it. 😄

**Comment by lanedirt** [comment]
Fixed by PR #397.
