### ISSUE TITLE
Add method to calculate current used fields (building levels) on planet

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#143]
For various features we will need a method that can calculate the amount of currently used fields on a planet. One example where this is shown is on the overview page as seen below.

I'm not sure yet how the amount of fields used should be calculated exactly. But this can probably be found out via wikis or basic reverse engineering.

TODO:
- [x] Add a method to `PlanetService` that calculates the amount of used fields on a planet and returns it as an int.
- [x] Use new method on overview page to show the current amount of fields used on the current planet.
- [x] Use new method on planet sidebar menu in planet tooltips.

![Image](https://github.com/lanedirt/OGameX/assets/6917405/2ade8014-7ee7-450c-a6b0-902598a439de)
![Image](https://github.com/lanedirt/OGameX/assets/6917405/c52343a1-13c8-493d-952f-ccd15882e6bb)

**Comment by Chewbaka69** [comment]
In other Ogame Clone, when you build a building, it increase the a field (field_current)
but an other approach can be to count on the fly the number of building level.

If planet type === Planet : sum level of building by type building && can be construct on Planet
else if planet type === Moon : sum level of building by type building && can be construct on Moon

**Comment by lanedirt** [comment]
> In other Ogame Clone, when you build a building, it increase the a field (field_current) but an other approach can be to count on the fly the number of building level.
> 
> If planet type === Planet : sum level of building by type building && can be construct on Planet else if planet type === Moon : sum level of building by type building && can be construct on Moon

I prefer the option to calculate this value on-the-fly. 👍  We could probably cache the value if performance becomes an issue (later). But being able to recalculate the value in case of issues with the initial calculation logic seems like the most optimal choice.

**Comment by jackbayliss** [comment]
I believe this one can be closed :)
