### ISSUE TITLE
Implement change playername popup logic

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#144]
When clicking on the playername in the top left corner a popup shows up where you can change your username.

Currently it only returns a static view by calling the `ChangeNickController::overlay()` method. POST requests don't work yet.

TODO:

- [ ] Implement playername change logic in `ChangeNickController`.

**Tip**: take a look at the code of `app/Http/Controllers/PlanetAbandonController.php`. This class already contains equivalent logic where it also does a password confirm check.

---

See screenshot below with what the view looks like now.

![Image](https://github.com/lanedirt/OGameX/assets/6917405/478cbd07-40f8-4b18-b604-2cff87889c4b)

**Comment by ghost** [comment]
Hi @lanedirt, Nice to meet you.

We don't know each other yet, but we aren't so far away from each other. Will find time to introduce me a bit later as its a story comment here 

FYI: i've started to work on this one and almost finished it, however i have a few questions

1. You have duplicate code regarding some functions related to this request already present, Can i in the same PR uniformalize these and delete duplicated code ?
2. You have the player username change in the settings menu as well, which is partially developed and miss quit some validation. Are you more favorable that i open another issue for these, or can i resolve it  within the same PR

Cheers

**Comment by lanedirt** [comment]
Hi @Jbaukens,

Nice to meet you. Thanks for your interest in helping out with this project, much appreciated! 👍 

Regarding your questions: both suggestions sound good to me. I'm all in favor for reducing duplicate code. Feel free to make all changes regarding changing of player names in the same PR and I'll take a look at it.

Looking forward to your contribution!

**Comment by ghost** [comment]
Thank you for your message. 

I finished it and will send a PR very soon. I might still have one additional question regarding the main concept of OGameX to avoid multiple reviews.

Is the end goal to reach the exact same as the official game ? For example, up to date, if i check on ogame.org

We do still have a password on the popup, but the password requirement has been removed for the settings view. Do we proceed with the same ? Do we keep it on the settings part as is, it is still present ?

We are not logged out anymore either when changing username (since we are using emails for sessions since a few years) Do you wanna keep the log out behavior or we skip it ?

Cheers

**Comment by lanedirt** [comment]
> Thank you for your message.
> 
> I finished it and will send a PR very soon. I might still have one additional question regarding the main concept of OGameX to avoid multiple reviews.
> 
> Is the end goal to reach the exact same as the official game ? For example, up to date, if i check on ogame.org
> 
> We do still have a password on the popup, but the password requirement has been removed for the settings view. Do we proceed with the same ? Do we keep it on the settings part as is, it is still present ?
> 
> We are not logged out anymore either when changing username (since we are using emails for sessions since a few years) Do you wanna keep the log out behavior or we skip it ?
> 
> Cheers

Sounds good! The goal for OGameX is to stay as true to the (current) original as possible. Some pages that are in this project have been taken from the official version between 2017-2019 and it's possible that since then these have changed on the official version. As is the case with your example of the password requirement in the settings view that has been removed.

In these cases feel free to change the current pages/logic in OGameX to match how the official version works as of right now.

Thanks for your attention to details, I appreciate that 😄 !
