### ISSUE TITLE
Add server settings popup

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#169]
Add server settings popup which displays actual server settings. A link should be added in the footer. 

The `SettingService` class can be used to retrieve dynamic settings from the database. Note: not all dynamic settings are available yet.  See `/admin/server-settings` page for settings that are defined at this moment.

Example:

<img width="425" alt="Screenshot 2024-05-19 at 11 01 50" src="https://github.com/lanedirt/OGameX/assets/6917405/c720451f-f9f7-482d-a9ac-49f4582fc0dc">

---

<img width="350" alt="Screenshot 2024-05-19 at 11 00 52" src="https://github.com/lanedirt/OGameX/assets/6917405/c05de7a5-d854-4b20-865d-f1e8b5551902">

**Comment by ghost** [comment]
Hi, 

I started to progress on that one. Taking small story's for the moment still discovering the code while i try to to make it work with my android application

Cheers

**Comment by lanedirt** [comment]
Sounds good 👍 , I'll assign the issue to you. Thanks!

**Comment by ghost** [comment]
Hi, 

Can you inform me how to proceed with the settings not available yet.  When reading #167 we might see 

 - Debries Field: 30%, 40%, 50%, 60%, 70%, 80% (the standard value is 30%).
 - DiDF- Defense into debris: 0, 30% 40% 50% 60%, 70% 80% (the standard is 0)

Can i assume these settings should be enums fields or free input fields, to be able to complete the server settings overlay.

![Screenshot from 2024-08-23 15-53-40](https://github.com/user-attachments/assets/466fc681-d72e-4f92-a5a3-949adeacf879)

Cheers

**Comment by lanedirt** [comment]
Hm, good question. Thanks for asking.

To be honest both options sound good to me. I think for simplicity free input fields will be sufficient. I do see adding enums / preset options a bonus which I think will help the admin user to know what the recommended option values are.

So in this case I'll leave it up to you to decide what you prefer (and how much time you have 😄).
