### ISSUE TITLE
[BUG] Galaxy page does not enable colony ship button when colony ship is available

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#177]
**Describe the bug**
The colony ship button should be enabled when a colony ship is present on the planet.

**To Reproduce**
1. Build a colony ship.
2. Go to the galaxy page.
3. The colony ship button should be enabled, but is not.

**Screenshots**
<img width="1018" alt="Screenshot 2024-05-19 at 12 00 05" src="https://github.com/lanedirt/OGameX/assets/6917405/8ac31c1f-2f87-423f-b6fd-c41c442196d2">

**Comment by Chewbaka69** [comment]
Will do it
