### ISSUE TITLE
Implement espionage report visibility limit based on espionage level

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#201]
Currently the espionage report shows all object types of the target, i.e.:

- Ships
- Defense
- Buildings
- Research

In the official game the level of "Espionage Technology" for the current player vs. target player determines which parts are shown and which parts are not. E.g. if the technology level of the target is (way) higher than the current player, only resources are shown and nothing else.

This visibility limitation feature will need to be implemented.

The logic that builds the espionage report can be found in:

- `app/GameMissions/EspionageMission.php` --> method `createEspionageReport()`.

**Comment by ghost** [comment]
Hi,

You can assign this to me aswell. I have already done the change and prepared the PR. I am just waiting to be able to send espionage missions to fetch the correct message being shown when the player is not eligible to view some information.

Cheers
