### ISSUE TITLE
[BUG] Galaxy page espionage button does not work

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#205]
**Describe the bug**
On the galaxy page there is a shortcut button to send a espionage probe to a foreign players planet. This button should enable if the current planet has one or more espionage probes ready.

**To Reproduce**
1. Make sure to have at least one espionage probe on the current planet.
2. Go to `Galaxy` page.
3. Find a planet of another player. (Hint: if there are no players, you can run the Laravel tests with `php artisan test` which will add multiple users as a result of running the tests.

**Expected behavior**
Expecting the espionage probe button to become active, and when clicked, to send a fleet with an espionage probe with mission "espionage" to the target planet.

**Screenshots**
<img width="1018" alt="Screenshot 2024-05-25 at 00 32 13" src="https://github.com/lanedirt/OGameX/assets/6917405/c7a7b384-3953-4824-9a3c-1f5c98e576cd">

**Comment by Chewbaka69** [comment]
Just to let you know, i am on it :)

**Comment by lanedirt** [comment]
> Just to let you know, i am on it :)

Awesome! I have assigned the issue to you so it's clear in the issue overview what's being worked on. Do you have enough rights to assign issues to yourself? If so, feel free to do so in the future. 😃  Thanks!

**Comment by Chewbaka69** [comment]
No i can not assign issue to myself

**Comment by lanedirt** [comment]
> No i can not assign issue to myself

Ok gotcha! Commenting is fine then 👍 !

**Comment by Chewbaka69** [comment]
You fix this bug on the last release

**Comment by lanedirt** [comment]
Hi @Chewbaka69, you're right it works now. Thanks for checking the status of this issue! 👍  Closing.
