### ISSUE TITLE
[BUG] Energy requirement check does not work when upgrading Space Dock Building

### ISSUE THREAD

**Issue by alican22** [lanedirt/OGameX#208]
Normally, I need to have at least 1.6K Energy to upgrade Space Dock.
![Screenshot 2567-05-26 at 12 50 12](https://github.com/lanedirt/OGameX/assets/7634657/0c0dba61-5be4-41ef-a91b-506977addbf2)

But I can upgrade successfully with -59 Energy (minus)
![Screenshot 2567-05-26 at 12 50 25](https://github.com/lanedirt/OGameX/assets/7634657/31052e59-03a2-43be-8143-25ad4f84ad98)

**Comment by lanedirt** [comment]
Hi @alican22,

Thanks for the bug report. I checked the current code and it seems we are indeed missing a check for the energy cost.

The existing checks look like this now:

app/Http/Controllers/Abstracts/AbstractBuildingsController line 92:
```php
  // Get object
  $object = $objects->getObjectByMachineName($object_machine_name);

  // Get current level of building
  $current_level = $this->planet->getObjectLevel($object_machine_name);

  // Check requirements of this building
  $requirements_met = $objects->objectRequirementsMet($object_machine_name, $this->planet, $player);

  // Check if the current planet has enough resources to build this building.
  $enough_resources = $this->planet->hasResources($objects->getObjectPrice($object_machine_name, $this->planet));
```

The planet->hasResources() method which checks if the current planet has enough resources seems to be missing an energy requirement check:
```php
    /**
     * Checks if this planet has equal or more than the requested resources.
     *
     * @param Resources $resources
     * Array with resources to check.
     *
     * @return bool
     */
    public function hasResources(Resources $resources): bool
    {
        if (!empty($resources->metal->get()) && $this->metal()->get() < $resources->metal->get()) {
            return false;
        }
        if (!empty($resources->crystal->get()) && $this->crystal()->get() < $resources->crystal->get()) {
            return false;
        }
        if (!empty($resources->deuterium->get()) && $this->deuterium()->get() < $resources->deuterium->get()) {
            return false;
        }

        return true;
    }
```

I'm not fully sure, but as far as I know the energy requirements works a little different than the normal resources. Normal resources (metal,crystal,deuterium) are deducted from the planet. But energy is more of a "check" if the total production energy production of the planet is at least X. So in your screenshot where it requires 1,6K energy it should not look at your current balance "-59" but rather it should look at the actual "current production" which is visible in the tooltip:

<img width="219" alt="Screenshot 2024-05-26 at 12 39 33" src="https://github.com/lanedirt/OGameX/assets/6917405/53267561-4265-4f66-843e-94b4f1d46e03">

I'm not entirely sure, but I think this is more or less how it should work.

**Comment by Chewbaka69** [comment]
I check on the real Ogame and you are right, the check in on the total production and energy and not the current balance:
![image](https://github.com/lanedirt/OGameX/assets/3535011/5227dd8d-162d-4092-8c93-65b8cbd3e73b)

**Comment by Chewbaka69** [comment]
duplicate #174
