### ISSUE TITLE
[BUG] Ships disappearing after deployment and transport mission

### ISSUE THREAD

**Issue by falisca** [lanedirt/OGameX#226]
### When i send an expedition for resources or deployment reasons, after the voyage is completed all the **ships** (light fighter and small cargo) _magically_ **disappear**.

--Issue test--

1) Send a fleet at one of your planet
2) Look if they come back or stay in the plant that u send them
3) After that the ships are **not** found.

After the trip they should become available again for the next mission, if they were not destroyed during it.

As u can see i received the materials from my transport
![Screenshot (3)](https://github.com/lanedirt/OGameX/assets/63355931/74e50ffa-65a1-4eea-9832-2b7e05081cce)

**Comment by lanedirt** [comment]
@falisca Thanks for reporting this bug. I tried to reproduce it on https://main.ogamex.dev and from my test I saw that the transport mission works correctly and returns the ships to the origin planet. But when I sent ships to another planet with the "Deployment" mission the ships did not get added to the target planet.

Is this also what you saw? I.e. that the problem is only caused by the "Deployment" mission?

**Comment by falisca** [comment]
Hi, @lanedirt  I tested on my production server: https://astri.sfu.si/ and both the transport and deployment missions makes ships disappearing. I do not know if the production server could be the problem.
By the way I like those one use ships 💯 ;)

**Comment by ElvisPretzel** [comment]
I just wanna add a thing, we are playing in the same server ( https://astri.sfu.si/ )
Tested this issue and I can tell that, when sending some ships together sometimes they don't come back home (on a transport mission) and sometimes they do...
I receive the resources but after that the ships vanish. If they go alone it works, maybe the issue could be when u send more than one type together?

**Comment by lanedirt** [comment]
@falisca  @ElvisPretzel I have just committed a fix to the main branch. Can you try this new version to see if the dissappearing ships is fixed?

Debug details:
From my tests I was able to reproduce that the deployment mission did not correctly add the units to the target planet. I have updated the unittests now so this usecase is properly covered for the future.

However I was not able to reproduce any issues with the transport mission. On my local machine I have sent around 30 transport missions and all ships arrived back at the planet I sent them from. If with this new version you still experience issues, feel free to reopen this issue. Thanks!

--

Btw, cool to see that you have deployed this project on your server. You're the first I know of 🚀 ! 😄

**Comment by ElvisPretzel** [comment]
@lanedirt I tried, and I can clearly say that it works. Every ship is back home and the resources too.
Thanks for the amazing work that you are currently doing!

We created the server just for fun with some other friends, you can join too just like anyone else.
We are glad to be the first from what it looks like...

You can join here ---> astri.sfu.si

We would be pleased to have you on our server as well. ;)
