### ISSUE TITLE
Implement attack mission and battle system logic

### ISSUE THREAD

**Issue by ElvisPretzel** [lanedirt/OGameX#233]
### When you go to attack someone the button to do so is **not** available and it says "no mission selected"

1. Go to Fleet
2. Click on some combat ships
3. Click on "Continue" and select the planet
4. You can see an error when u want to select the mission "Attack"

You should be able to attack someone even with only 1 ship

![Screenshot (11)](https://github.com/lanedirt/OGameX/assets/173049218/d81a9926-8449-4141-ad02-9dda7f5c9399)

**Comment by lanedirt** [comment]
Thanks for the issue report! This is correct, the attack mission and battle system logic is not implemented yet. Therefore it doesn't show up yet on the fleet dispatch screen.

I'll change the label to mark this as an enhancement. 

This is one of the next major milestones for this project to implement.

**Comment by ElvisPretzel** [comment]
Ops sorry I didn't realize, you are right

Amazing work anyway! ;)
