### ISSUE TITLE
[BUG] Hide defense properties that are not relevant in "?" popup

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#291]
**Describe the bug**
Certain properties do not apply to defense objects, these are: speed, cargo capacity and fuel usage.

**To Reproduce**
1. Go to Defense.
2. Click on rocket launcher then click on the "?" button.

**Expected behavior**
Expecting the above mentioned properties to not show up for defense objects.

**Screenshots**
<img width="812" alt="Screenshot 2024-08-19 at 13 38 39" src="https://github.com/user-attachments/assets/078dd91b-e429-4f50-8c66-84823bc2358c">

**Additional context**
The template for this popup can be found in `resources/views/ingame/techtree/info/properties.blade.php`. The additional logic can most likely be added, perhaps in combination with a change in the controller which is located in `app/Http/Controllers/TechtreeController.php`.

**Comment by jackbayliss** [comment]
@lanedirt  This can now be closed as it's resolved. :)
