### ISSUE TITLE
[BUG] Can't follow install steps 

### ISSUE THREAD

**Issue by TheChaser5** [lanedirt/OGameX#302]
**Describe the bug**

When I want to go to step 
`
    Run Laravel setup commands to download composer dependencies, generate an encryption key and prepare the database:

$ composer install
$ php artisan key:generate
$ php artisan migrate
`

`ogame@ogame:~/ogamex$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php ^8.2 but your php version (8.1.2) does not satisfy that requirement.
  Problem 2
    - laravel/framework is locked to version v11.20.0 and an update of this package was not requested.
    - laravel/framework v11.20.0 requires php ^8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 3
    - nunomaduro/termwind is locked to version v2.0.1 and an update of this package was not requested.
    - nunomaduro/termwind v2.0.1 requires php ^8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 4
    - symfony/clock is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/clock v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 5
    - symfony/console is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/console v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 6
    - symfony/css-selector is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/css-selector v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 7
    - symfony/error-handler is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/error-handler v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 8
    - symfony/event-dispatcher is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/event-dispatcher v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 9
    - symfony/finder is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/finder v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 10
    - symfony/http-foundation is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/http-foundation v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 11
    - symfony/http-kernel is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/http-kernel v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 12
    - symfony/mailer is locked to version v7.1.2 and an update of this package was not requested.
    - symfony/mailer v7.1.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 13
    - symfony/mime is locked to version v7.1.2 and an update of this package was not requested.
    - symfony/mime v7.1.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 14
    - symfony/process is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/process v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 15
    - symfony/routing is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/routing v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 16
    - symfony/string is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/string v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 17
    - symfony/translation is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/translation v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 18
    - symfony/uid is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/uid v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 19
    - symfony/var-dumper is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/var-dumper v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 20
    - tijsverkoyen/css-to-inline-styles is locked to version v2.2.7 and an update of this package was not requested.
    - tijsverkoyen/css-to-inline-styles v2.2.7 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 21
    - brianium/paratest is locked to version v7.5.2 and an update of this package was not requested.
    - brianium/paratest v7.5.2 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 22
    - laravel/pint is locked to version v1.17.2 and an update of this package was not requested.
    - laravel/pint v1.17.2 requires ext-xml * -> it is missing from your system. Install or enable PHP's xml extension.
  Problem 23
    - nunomaduro/collision is locked to version v8.4.0 and an update of this package was not requested.
    - nunomaduro/collision v8.4.0 requires php ^8.2.0 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 24
    - phar-io/manifest is locked to version 2.0.4 and an update of this package was not requested.
    - phar-io/manifest 2.0.4 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 25
    - phpunit/php-code-coverage is locked to version 11.0.5 and an update of this package was not requested.
    - phpunit/php-code-coverage 11.0.5 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 26
    - phpunit/php-file-iterator is locked to version 5.0.1 and an update of this package was not requested.
    - phpunit/php-file-iterator 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 27
    - phpunit/php-invoker is locked to version 5.0.1 and an update of this package was not requested.
    - phpunit/php-invoker 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 28
    - phpunit/php-text-template is locked to version 4.0.1 and an update of this package was not requested.
    - phpunit/php-text-template 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 29
    - phpunit/php-timer is locked to version 7.0.1 and an update of this package was not requested.
    - phpunit/php-timer 7.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 30
    - phpunit/phpunit is locked to version 11.3.1 and an update of this package was not requested.
    - phpunit/phpunit 11.3.1 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 31
    - sebastian/cli-parser is locked to version 3.0.2 and an update of this package was not requested.
    - sebastian/cli-parser 3.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 32
    - sebastian/code-unit is locked to version 3.0.1 and an update of this package was not requested.
    - sebastian/code-unit 3.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 33
    - sebastian/code-unit-reverse-lookup is locked to version 4.0.1 and an update of this package was not requested.
    - sebastian/code-unit-reverse-lookup 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 34
    - sebastian/comparator is locked to version 6.0.2 and an update of this package was not requested.
    - sebastian/comparator 6.0.2 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 35
    - sebastian/complexity is locked to version 4.0.1 and an update of this package was not requested.
    - sebastian/complexity 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 36
    - sebastian/diff is locked to version 6.0.2 and an update of this package was not requested.
    - sebastian/diff 6.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 37
    - sebastian/environment is locked to version 7.2.0 and an update of this package was not requested.
    - sebastian/environment 7.2.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 38
    - sebastian/exporter is locked to version 6.1.3 and an update of this package was not requested.
    - sebastian/exporter 6.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 39
    - sebastian/global-state is locked to version 7.0.2 and an update of this package was not requested.
    - sebastian/global-state 7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 40
    - sebastian/lines-of-code is locked to version 3.0.1 and an update of this package was not requested.
    - sebastian/lines-of-code 3.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 41
    - sebastian/object-enumerator is locked to version 6.0.1 and an update of this package was not requested.
    - sebastian/object-enumerator 6.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 42
    - sebastian/object-reflector is locked to version 4.0.1 and an update of this package was not requested.
    - sebastian/object-reflector 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 43
    - sebastian/recursion-context is locked to version 6.0.2 and an update of this package was not requested.
    - sebastian/recursion-context 6.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 44
    - sebastian/type is locked to version 5.0.1 and an update of this package was not requested.
    - sebastian/type 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 45
    - sebastian/version is locked to version 5.0.1 and an update of this package was not requested.
    - sebastian/version 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 46
    - spatie/laravel-ignition is locked to version 2.8.0 and an update of this package was not requested.
    - spatie/laravel-ignition 2.8.0 requires ext-curl * -> it is missing from your system. Install or enable PHP's curl extension.
  Problem 47
    - symfony/yaml is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/yaml v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 48
    - theseer/tokenizer is locked to version 1.2.3 and an update of this package was not requested.
    - theseer/tokenizer 1.2.3 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 49
    - symfony/http-foundation v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
    - spatie/flare-client-php 1.7.0 requires symfony/http-foundation ^5.2|^6.0|^7.0 -> satisfiable by symfony/http-foundation[v7.1.3].
    - spatie/flare-client-php is locked to version 1.7.0 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-intl.ini
    - /etc/php/8.1/cli/conf.d/20-mbstring.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-xml --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-curl --ignore-platform-req=ext-dom` to temporarily ignore these required extensions.
`

**To Reproduce**
Follow the steps on a clean ubuntu 22.04.04

**Expected behavior**
Installation of the program

**Screenshots**
`ogame@ogame:~/ogamex$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php ^8.2 but your php version (8.1.2) does not satisfy that requirement.
  Problem 2
    - laravel/framework is locked to version v11.20.0 and an update of this package was not requested.
    - laravel/framework v11.20.0 requires php ^8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 3
    - nunomaduro/termwind is locked to version v2.0.1 and an update of this package was not requested.
    - nunomaduro/termwind v2.0.1 requires php ^8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 4
    - symfony/clock is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/clock v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 5
    - symfony/console is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/console v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 6
    - symfony/css-selector is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/css-selector v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 7
    - symfony/error-handler is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/error-handler v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 8
    - symfony/event-dispatcher is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/event-dispatcher v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 9
    - symfony/finder is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/finder v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 10
    - symfony/http-foundation is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/http-foundation v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 11
    - symfony/http-kernel is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/http-kernel v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 12
    - symfony/mailer is locked to version v7.1.2 and an update of this package was not requested.
    - symfony/mailer v7.1.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 13
    - symfony/mime is locked to version v7.1.2 and an update of this package was not requested.
    - symfony/mime v7.1.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 14
    - symfony/process is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/process v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 15
    - symfony/routing is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/routing v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 16
    - symfony/string is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/string v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 17
    - symfony/translation is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/translation v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 18
    - symfony/uid is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/uid v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 19
    - symfony/var-dumper is locked to version v7.1.3 and an update of this package was not requested.
    - symfony/var-dumper v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 20
    - tijsverkoyen/css-to-inline-styles is locked to version v2.2.7 and an update of this package was not requested.
    - tijsverkoyen/css-to-inline-styles v2.2.7 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 21
    - brianium/paratest is locked to version v7.5.2 and an update of this package was not requested.
    - brianium/paratest v7.5.2 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 22
    - laravel/pint is locked to version v1.17.2 and an update of this package was not requested.
    - laravel/pint v1.17.2 requires ext-xml * -> it is missing from your system. Install or enable PHP's xml extension.
  Problem 23
    - nunomaduro/collision is locked to version v8.4.0 and an update of this package was not requested.
    - nunomaduro/collision v8.4.0 requires php ^8.2.0 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 24
    - phar-io/manifest is locked to version 2.0.4 and an update of this package was not requested.
    - phar-io/manifest 2.0.4 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 25
    - phpunit/php-code-coverage is locked to version 11.0.5 and an update of this package was not requested.
    - phpunit/php-code-coverage 11.0.5 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 26
    - phpunit/php-file-iterator is locked to version 5.0.1 and an update of this package was not requested.
    - phpunit/php-file-iterator 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 27
    - phpunit/php-invoker is locked to version 5.0.1 and an update of this package was not requested.
    - phpunit/php-invoker 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 28
    - phpunit/php-text-template is locked to version 4.0.1 and an update of this package was not requested.
    - phpunit/php-text-template 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 29
    - phpunit/php-timer is locked to version 7.0.1 and an update of this package was not requested.
    - phpunit/php-timer 7.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 30
    - phpunit/phpunit is locked to version 11.3.1 and an update of this package was not requested.
    - phpunit/phpunit 11.3.1 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 31
    - sebastian/cli-parser is locked to version 3.0.2 and an update of this package was not requested.
    - sebastian/cli-parser 3.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 32
    - sebastian/code-unit is locked to version 3.0.1 and an update of this package was not requested.
    - sebastian/code-unit 3.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 33
    - sebastian/code-unit-reverse-lookup is locked to version 4.0.1 and an update of this package was not requested.
    - sebastian/code-unit-reverse-lookup 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 34
    - sebastian/comparator is locked to version 6.0.2 and an update of this package was not requested.
    - sebastian/comparator 6.0.2 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 35
    - sebastian/complexity is locked to version 4.0.1 and an update of this package was not requested.
    - sebastian/complexity 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 36
    - sebastian/diff is locked to version 6.0.2 and an update of this package was not requested.
    - sebastian/diff 6.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 37
    - sebastian/environment is locked to version 7.2.0 and an update of this package was not requested.
    - sebastian/environment 7.2.0 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 38
    - sebastian/exporter is locked to version 6.1.3 and an update of this package was not requested.
    - sebastian/exporter 6.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 39
    - sebastian/global-state is locked to version 7.0.2 and an update of this package was not requested.
    - sebastian/global-state 7.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 40
    - sebastian/lines-of-code is locked to version 3.0.1 and an update of this package was not requested.
    - sebastian/lines-of-code 3.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 41
    - sebastian/object-enumerator is locked to version 6.0.1 and an update of this package was not requested.
    - sebastian/object-enumerator 6.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 42
    - sebastian/object-reflector is locked to version 4.0.1 and an update of this package was not requested.
    - sebastian/object-reflector 4.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 43
    - sebastian/recursion-context is locked to version 6.0.2 and an update of this package was not requested.
    - sebastian/recursion-context 6.0.2 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 44
    - sebastian/type is locked to version 5.0.1 and an update of this package was not requested.
    - sebastian/type 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 45
    - sebastian/version is locked to version 5.0.1 and an update of this package was not requested.
    - sebastian/version 5.0.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 46
    - spatie/laravel-ignition is locked to version 2.8.0 and an update of this package was not requested.
    - spatie/laravel-ignition 2.8.0 requires ext-curl * -> it is missing from your system. Install or enable PHP's curl extension.
  Problem 47
    - symfony/yaml is locked to version v7.1.1 and an update of this package was not requested.
    - symfony/yaml v7.1.1 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 48
    - theseer/tokenizer is locked to version 1.2.3 and an update of this package was not requested.
    - theseer/tokenizer 1.2.3 requires ext-dom * -> it is missing from your system. Install or enable PHP's dom extension.
  Problem 49
    - symfony/http-foundation v7.1.3 requires php >=8.2 -> your php version (8.1.2) does not satisfy that requirement.
    - spatie/flare-client-php 1.7.0 requires symfony/http-foundation ^5.2|^6.0|^7.0 -> satisfiable by symfony/http-foundation[v7.1.3].
    - spatie/flare-client-php is locked to version 1.7.0 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-intl.ini
    - /etc/php/8.1/cli/conf.d/20-mbstring.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-xml --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-dom --ignore-platform-req=ext-curl --ignore-platform-req=ext-dom` to temporarily ignore these required extensions.
`

**Comment by lanedirt** [comment]
Hi @TheChaser5,

Are you trying to run OGameX with the (recommended) docker compose stack, or are you trying to run it natively on a machine?

Based on the errors it seems the way you are running `composer install` its detecting PHP 8.1 on your machine while it needs at least PHP version 8.2. Based on these specific errors updating PHP on your Ubuntu machine should help. You can follow the official Laravel instructions which also mentions PHP v8.2+ as a requirement:
https://laravel.com/docs/11.x/deployment

Btw, if you don't have a particular reason not to use Docker, my advice would be to use the Docker Compose stack as this gives you the benefit that all versions of dependencies such as PHP, the database etc. are ensured to work together now and with future updates. This saves you the hassle of maintaining it yourself.  If you need more help, feel free to let me know.

**Comment by TheChaser5** [comment]
Hello Lanedirt,

Thank you for your quick reply
I'm following the install instructions.

    Clone the repository.
    Copy .env.example to .env.
    Launch the project using Docker Compose:

$ docker compose up -d


Did it install the wrong php version in it?

**Comment by lanedirt** [comment]
Hi, those steps should be correct. Can you check if you are actually inside the Docker container when you are running the composer / artisan commands?

This step (4) is important:

```
$ docker exec -it ogame-app /bin/bash
```

With this command you go into the docker container which has the right version of PHP inside of it necessary for running the setup commands. Once you are inside this container you then run these commands:

```
$ composer install
$ php artisan key:generate
$ php artisan migrate
```

With this sequence it should work. Can you try it again?

**Comment by TheChaser5** [comment]
I'm sorry, that seemed to be the problem!!
Thank you!

**Comment by lanedirt** [comment]
Good to hear that was the solution 👍 . Good luck with finishing setting up your server!
