### ISSUE TITLE
Remove social links from outgame template

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#346]
The outgame template contains icons with links to social media (Google+, Facebook) that should be removed. The icons can stay but the links should removed or set to `#`.
<img width="524" alt="Screenshot 2024-09-13 at 21 17 51" src="https://github.com/user-attachments/assets/fe77609e-c0cf-48ce-b3bd-5d609bedbd70">

**Comment by alican22** [comment]
#351 its a minor commit but needed :)

**Comment by lanedirt** [comment]
Fixed by #351.
