### ISSUE TITLE
[BUG] Hyperspace technology and hyperspace drive technology requirements are incorrectly defined

### ISSUE THREAD

**Issue by lanedirt** [lanedirt/OGameX#376]
**Describe the bug**
The hyperspace technology and hyperspace drive research technology requirements are not correct. With research lab set to level 0 both technologies are able to be upgraded to the next level.

**To Reproduce**
1. Via "Developer shortcuts" when logged in as admin, set all buildings to level 0 and all research to level 10.
2. Go to "research" page.
3. When you have enough resources (>10M metal, 20M crystal, 6M deuterium) the hyperspace technology and hyperspace drive show as possible to research while the "research lab" building is set to level 0.

**Expected behavior**
I expect the research to show as "Requirements not met" because both should require research lab level 7.

**Screenshots**
<img width="681" alt="Screenshot 2024-10-04 at 09 46 10" src="https://github.com/user-attachments/assets/01f5feae-86d3-4bb5-a30b-b6fd11d046c5">

**Additional context**
All technology/research game objects are defined in the following file:

```
app/GameObjects/ResearchObjects.php
```

The requirements of each research object can be adjusted via the `requirements` property. The correct research lab level should be added to the hyperspace technology and hyperspace drive objects.

**Comment by jackbayliss** [comment]
@lanedirt  you can assign this to me :)
