### ISSUE TITLE
Discord Link is invalid

### ISSUE THREAD

**Issue by dglassow** [lanedirt/OGameX#399]
The invite link has expired.  MvDzTNpc

**Comment by dglassow** [comment]
Can't modify label, but obviously this is Documentation and not a bug. I'd like to get into the discord so I can better collaborate there.

**Comment by lanedirt** [comment]
Hi @dglassow,

Thanks for reporting! I indeed noticed there were two links. I already updated one of them not too long ago but forgot to update the second one as well. Now it should work 😄 !
