### ISSUE TITLE
Decrease building & research levels button

### ISSUE THREAD

**Issue by alican22** [lanedirt/OGameX#435]
Original ogame has decrease buildings and research by tear down button. 

When you decrease the building or research you will get refund 62.5% resources amount.

![Screenshot 2567-11-01 at 23 21 33](https://github.com/user-attachments/assets/fd140cb7-ce68-438d-a9a7-c41f47c126ba)

**Comment by lanedirt** [comment]
Hi @alican22,

Thanks for reporting this issue. There already is an issue created for this however, see:
- #110 

Also you mention that a refund of 62.5% resources is given. I actually thought that in the official game it costs resources to downgrade. I.e. you don't get anything back but instead you have to pay more. But I might have that wrong, haven't really used this functionality when I played the game.

Can you add any comments or extra context you might have to the original issue above?

Closing this as duplicate.

**Comment by alican22** [comment]
> * Implement building downgrade/tear down functionality #110

Hi @lanedirt 

Absulately you are right. It's not refund and resource. It has to be pay more 62.5% more from the level that you upgraded.
