### ISSUE TITLE
[BUG] Solar Satellite Construction Only Builds One Unit Regardless of Quantity

### ISSUE THREAD

**Issue by aDwCarrazzone** [lanedirt/OGameX#456]
**Describe the bug**
When attempting to build more than one Solar Satellite, only a single unit is constructed, regardless of the requested quantity. For example, if the user queues 5 Solar Satellites for construction, only 1 is built, and the remaining units are not processed. This issue occurs consistently whenever multiple Solar Satellites are queued for construction.

**To Reproduce**
1.Go to the shipyard or the relevant Solar Satellite construction page.
2.Select Solar Satellite as the type of unit to construct.
3.Enter a quantity greater than 1 (e.g., 5 units).
4.Confirm the construction order and wait for the process to complete.
5.Observe the final number of Solar Satellites constructed, which will always be 1, regardless of the quantity entered.

**Expected behavior**
The expected behavior is that the exact number of Solar Satellites requested for construction should be built and reflected in the fleet count. For example, if 5 Solar Satellites are ordered, all 5 units should be queued and built in sequence until the requested amount is completed.

**Screenshots**
Before:
![image](https://github.com/user-attachments/assets/e096c70c-34d4-400c-9ff1-ec07b34de19a)
After:
![image](https://github.com/user-attachments/assets/42f3fcc1-51f4-4b07-9bc9-7e02e4d31cdd)

**Comment by aDwCarrazzone** [comment]
duplicate

**Comment by lanedirt** [comment]
Hi @aDwCarrazzone,

Thanks for taking the time to report this issue, indeed there is already being work done on this in #436. I'm hoping to merge that PR today so work can continue on further polishing the behavior caused by this issue.
