### ISSUE TITLE
[BUG] Colony Abandonment Not Functioning

### ISSUE THREAD

**Issue by aDwCarrazzone** [lanedirt/OGameX#459]
**Describe the bug**
When attempting to abandon a colony its not being abandoned and the colony remains active.

**To Reproduce**
1. Navigate to the Abandon/Rename page for a colony.
2. Click the "Abandon Colony" button.
3. Enter the correct account password in the prompt to confirm the action.
4. Observe that no changes occur—the colony is not abandoned, and the interface remains unchanged.

**Expected behavior**
After entering the correct password and confirming the abandonment, the colony should be removed from the player’s active colonies, and the player should receive confirmation of the action.

**Screenshots**
![image](https://github.com/user-attachments/assets/6f3ed720-6ecb-426c-b568-4a3a699102e9)
![image](https://github.com/user-attachments/assets/441e3fb8-723d-4a07-9f67-af878c21a0f4)

**Additional context**
- Entering the password and confirming the abandonment does not result in any changes to the colony status.
- No error messages or confirmation prompts are displayed to indicate whether the action succeeded or failed.

**Comment by lanedirt** [comment]
Hi @aDwCarrazzone,

Thanks for the bug report. I just tried to reproduce this on my local environment with a new account but for me it works. Here is a screen recording showing what the happy path looks like:
![ScreenRecording2024-11-23at21 26 37-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/88093bc9-5c59-46ac-9152-b3c2983a7397)

So unfortunately I cannot reproduce this locally. Do you see any errors in the JS console or can you try to debug the HTTP request from the network tab to see the internal error (on localhost)?

**Comment by aDwCarrazzone** [comment]
Well, i really don't know what happened before but i tried again and it worked.
