### ISSUE TITLE
[BUG] "lastBuildingSlot is not defined" error when attempting to construct in Shipyard / Defense after building a Terraformer.

### ISSUE THREAD

**Issue by SuGolYolLom** [lanedirt/OGameX#485]
**Describe the bug**
After constructing a Terraformer on any planet, the Shipyard becomes unusable on all planets. Attempting to construct in the Shipyard results in the error "lastBuildingSlot is not defined," preventing users from building ships.

**To Reproduce**
1. Go to any planet where the Shipyard / Defense is operational, before building the Terraformer (any planet)
2. Verify that the Shipyard / Defense works by constructing a ship, such as a Solar Satellite.
3. Build a Terraformer on any planet.
4. After the Terraformer finishes construction, go to the Shipyard on any planet.
5. Attempt to use the Shipyard / Defense, attempt to build a LC, SS
6. lastBuildingSlot is not defined error shows in console

**Observed Result:**
The Shipyard cannot be used, and the error message "lastBuildingSlot is not defined" is displayed (console)

**Expected Result:**
The Shipyard should remain operational, allowing users to build ships as expected, even after constructing a Terraformer.

**Screenshots**
![image](https://github.com/user-attachments/assets/0fa15bfa-db0b-402c-b817-b9ca0e61abbd)

**Additional context**
Uncaught ReferenceError: lastBuildingSlot is not defined
    onClickUpgrade https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:84098
    dispatch https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:3
    handle https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:3
    add https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:3
    sa https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:3
    each https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:2
    each https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:2
    sa https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:3
    on https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:3
    <anonymous> https://main.ogamex.dev/js/ingame.min.js?id=f7ca8c70d70904454426ad83cb49783f:66253
ingame.min.js:84098:7

TechnologyDetails.prototype.onClickUpgrade = function (e) {
  let technologyId = $(e.currentTarget).data('technology');
  let amount = $('#build_amount').val() || 1;

  if (planetMoveInProgress) {
    return errorBoxDecision(LocalizationStrings.attention, LocalizationStrings.planetMoveBreakUpWarning, LocalizationStrings.yes, LocalizationStrings.no, function () {
      buildListActionBuild(technologyId, amount);
    });
  }

  if (lastBuildingSlot.showWarning == true) { // FAILS HERE
    return errorBoxDecision(LocalizationStrings.notice, lastBuildingSlot.slotWarning, LocalizationStrings.yes, LocalizationStrings.no, function () {
      buildListActionBuild(technologyId, amount);
    });
  }

  if (showLifeformBonusCapReached) {
    return errorBoxDecision(LocalizationStrings.attention, this.loca.LOCA_LIFEFORM_BONUS_CAP_REACHED_WARNING, LocalizationStrings.yes, LocalizationStrings.no, function () {
      buildListActionBuild(technologyId, amount);
    });
  }

  buildListActionBuild(technologyId, amount);
};

**Comment by lanedirt** [comment]
Thanks for submitting this bug! Look like this is a regression caused by the recent moon update. I'll look into it!

**Comment by lanedirt** [comment]
@SuGolYolLom Issue should be fixed now on https://main.ogamex.dev. Thanks for taking the time to report it!
